import { listImportantDates, listNotificationSettings } from "../../../db/notification-store";
import { requireAdmin } from "../auth";

export const dynamic = "force-dynamic";

const labels: Record<string, { title: string; description: string }> = {
  planner_finalized: { title: "志願完成通知", description: "使用者完成志願規劃後發送 LINE 通知。" },
  score_calculated: { title: "成績試算完成通知", description: "使用者完成成績試算後發送 LINE 通知。" },
  important_date: { title: "重要日期通知", description: "重要日期到達設定時間後發送提醒。" },
};

export default async function NotificationsPage({ searchParams }: { searchParams: Promise<{ updated?: string }> }) {
  await requireAdmin();
  const [settings, importantDates] = await Promise.all([listNotificationSettings(), listImportantDates(true)]);
  const params = await searchParams;
  return <><section className="admin-page-heading"><div><p className="admin-eyebrow">Operations / Notifications</p><h1>通知中心</h1><p className="admin-muted">管理 LINE 通知模板與官方升學時程；前台只會顯示啟用中的日期。</p></div></section>{params.updated ? <section className="admin-flash">{flashMessage(params.updated)}</section> : null}<section className="admin-module-stack">{settings.map((setting) => { const label = labels[setting.event_key] || { title: setting.event_key, description: "後台通知事件。" }; return <form className="admin-panel admin-setting-row" key={setting.event_key} action="/api/admin/notifications" method="post"><input type="hidden" name="action" value="settings" /><input type="hidden" name="event_key" value={setting.event_key} /><div className="admin-setting-heading"><div><h2>{label.title}</h2><p className="admin-muted">{label.description}</p></div><label className="admin-switch"><input name="enabled" type="checkbox" defaultChecked={setting.enabled === 1} /> <span>{setting.enabled ? "已開啟" : "已關閉"}</span></label></div><label>通知標題<input name="title" defaultValue={setting.title} maxLength={100} required /></label><label>通知內容<textarea name="body_template" defaultValue={setting.body_template} rows={4} maxLength={1000} required /></label><details><summary>進階設定</summary><p className="admin-muted">Event ID：<code>{setting.event_key}</code> · 可用變數：<code>{setting.event_key === "planner_finalized" ? "{count}" : setting.event_key === "score_calculated" ? "{district} {academicYear} {score}" : "{title} {description} {eventDate}"}</code></p></details><button className="admin-button" type="submit">儲存通知設定</button></form>; })}</section><section className="admin-panel admin-module-form"><div className="admin-section-head"><div><p className="admin-eyebrow">Important dates</p><h2>新增官方時程</h2></div><span className="admin-badge ok">{importantDates.filter((item) => item.enabled).length} 筆啟用</span></div><p className="admin-muted">日期以台北時區輸入；發送時間到達後，已開通「重要日期」的 LINE 會員會收到提醒。沒有正式公告時請停用，避免前台誤解。</p><DateForm /></section><section className="admin-module-stack"><div className="admin-section-head"><div><p className="admin-eyebrow">Schedule registry</p><h2>已建立的時程</h2></div><span className="admin-badge">{importantDates.length} 筆（含停用）</span></div>{importantDates.map((item) => <DateForm key={item.id} item={item} />)}{!importantDates.length ? <p className="admin-panel admin-muted">目前沒有時程資料。</p> : null}</section></>;
}

function DateForm({ item }: { item?: Awaited<ReturnType<typeof listImportantDates>>[number] }) {
  return <div className="admin-panel admin-setting-row"><form action="/api/admin/notifications" method="post"><input type="hidden" name="action" value={item ? "update_date" : "create_date"} />{item ? <input type="hidden" name="id" value={item.id} /> : null}<div className="admin-setting-heading"><div><h2>{item ? item.title : "建立一筆時程"}</h2><p className="admin-muted">{item ? `ID：${item.id} · 最後更新 ${formatDate(item.updated_at)} · ${item.updated_by}` : "官方公告、報名、選填與放榜等日期。"}</p></div><label className="admin-switch"><input name="enabled" type="checkbox" defaultChecked={item ? item.enabled === 1 : true} /> <span>{item ? (item.enabled ? "前台啟用" : "已停用") : "建立後啟用"}</span></label></div><label>事件標題<input name="title" defaultValue={item?.title} maxLength={100} required placeholder="例如：志願選填開始" /></label><label>說明<textarea name="description" defaultValue={item?.description} rows={3} maxLength={1000} placeholder="提醒學生現在要準備什麼" /></label><div className="admin-dashboard-columns"><label>事件日期<input name="event_date" type="date" defaultValue={item?.event_date} required /></label><label>LINE 發送時間（台北）<input name="send_at" type="datetime-local" defaultValue={item ? toTaipeiInput(item.send_at) : undefined} required /></label></div><button className="admin-button" type="submit">{item ? "儲存時程" : "新增時程"}</button></form>{item ? <form className="admin-row-actions" action="/api/admin/notifications" method="post"><input type="hidden" name="action" value="delete_date" /><input type="hidden" name="id" value={item.id} /><button className="admin-button admin-button-danger" type="submit">刪除</button></form> : null}{item?.sent_at ? <p className="admin-muted">已發送：{formatDate(item.sent_at)}；重新儲存會重設發送狀態。</p> : <p className="admin-muted">尚未發送。前台會顯示日期狀態，推播由排程工作執行。</p>}</div>;
}

function toTaipeiInput(value: string) { const date = new Date(value); if (Number.isNaN(date.getTime())) return ""; const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Taipei", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(date); const get = (type: string) => parts.find((part) => part.type === type)?.value || ""; return `${get("year")}-${get("month")}-${get("day")}T${get("hour").padStart(2, "0")}:${get("minute")}`; }
function formatDate(value: string) { return new Intl.DateTimeFormat("zh-TW", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Taipei" }).format(new Date(value)); }
function flashMessage(value: string) { return ({ notifications: "通知設定已儲存。", notifications_invalid: "通知設定格式不正確，尚未儲存。", important_date: "重要時程已更新。", important_date_invalid: "日期或發送時間格式不正確，尚未儲存。" } as Record<string, string>)[value] || "操作完成。"; }
