const districts = [
  ["tp", "基北區", "臺北市、新北市、基隆市"], ["ilan", "宜蘭區", "宜蘭縣"],
  ["taoyuan-lienchiang", "桃連區", "桃園市、連江縣"], ["hsinchu-miaoli", "竹苗區", "新竹市、新竹縣、苗栗縣"],
  ["ct", "中投區", "臺中市、南投縣"], ["changhua", "彰化區", "彰化縣"],
  ["yunlin", "雲林區", "雲林縣"], ["chiayi", "嘉義區", "嘉義市、嘉義縣"], ["tainan", "臺南區", "臺南市"],
  ["kaohsiung", "高雄區", "高雄市"], ["pingtung", "屏東區", "屏東縣"], ["hualien", "花蓮區", "花蓮縣"],
  ["taitung", "臺東區", "臺東縣"], ["penghu", "澎湖區", "澎湖縣"], ["kinmen", "金門區", "金門縣"],
];

export default function HomePage() {
  return <main className="home-page min-h-screen bg-[#f7f9fd] text-[#17233b]">
    <header className="mx-auto flex w-[min(1160px,calc(100%-32px))] items-center justify-between gap-4 py-5">
      <a className="flex items-center gap-2 font-bold tracking-tight" href="#top"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#173d78] text-lg text-white">↗</span>全國國中升學資訊網</a>
      <nav className="hidden gap-6 text-sm font-semibold text-slate-500 md:flex"><a href="#districts">選擇就學區</a><a href="#tools">升學工具</a><a href="#pathways">升學路徑</a></nav>
      <a className="rounded-xl bg-[#173d78] px-4 py-2.5 text-sm font-bold text-white" href="#districts">查詢學校</a>
    </header>
    <section id="top" className="border-y border-blue-100 bg-gradient-to-br from-white via-[#eef5ff] to-[#e5f0ff] py-16 md:py-24">
      <div className="mx-auto grid w-[min(1160px,calc(100%-32px))] items-center gap-10 lg:grid-cols-[1.2fr_.8fr]">
        <div><p className="mb-3 text-xs font-extrabold tracking-[.16em] text-[#2868d7]">全國國中升學服務平台</p><h1 className="max-w-3xl text-5xl font-extrabold leading-tight tracking-[-.05em] md:text-7xl">先選對地區，<br/><span className="text-[#2868d7]">再走好下一步。</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-500">從全區學校查詢、積分試算到志願分析，把升學規劃整理成每一步都看得懂的選擇。</p><div className="mt-8 flex flex-wrap gap-3"><a className="rounded-xl bg-[#2868d7] px-5 py-3.5 font-bold text-white shadow-lg shadow-blue-200" href="#districts">選擇就學區，查詢學校 →</a><a className="rounded-xl border border-slate-200 bg-white px-5 py-3.5 font-bold text-[#173d78]" href="#tools">查看升學工具</a></div></div>
        <aside className="rounded-3xl bg-[#173d78] p-8 text-white shadow-2xl shadow-blue-950/15"><p className="text-sm font-bold text-blue-200">升學規劃，從這三步開始</p><ol className="mt-6 space-y-5"><li className="flex gap-3"><b className="text-sm text-blue-300">01</b><div><strong>選擇就學區</strong><small className="block text-sm text-blue-100">確認所在地區的招生範圍</small></div></li><li className="flex gap-3"><b className="text-sm text-blue-300">02</b><div><strong>查詢學校與科別</strong><small className="block text-sm text-blue-100">依學制、地區與關鍵字篩選</small></div></li><li className="flex gap-3"><b className="text-sm text-blue-300">03</b><div><strong>試算並安排志願</strong><small className="block text-sm text-blue-100">掌握積分、落點與志願策略</small></div></li></ol></aside>
      </div>
    </section>
    <div className="bg-[#173d78] py-4 text-white"><div className="mx-auto flex w-[min(1160px,calc(100%-32px))] flex-wrap gap-x-12 gap-y-2 text-sm"><span><b>全區開放</b>　學校查詢</span><span><b>依區載入</b>　積分試算</span><span><b>核心保留</b>　志願分析</span></div></div>
    <section id="districts" className="mx-auto w-[min(1160px,calc(100%-32px))] py-20"><p className="text-xs font-extrabold tracking-[.16em] text-[#2868d7]">第一步</p><div className="mt-3 flex flex-col justify-between gap-4 md:flex-row md:items-end"><h2 className="text-4xl font-extrabold tracking-[-.05em]">選擇你的就學區</h2><p className="max-w-md text-slate-500">全區學校查詢已開放；選擇後可進入對應的學校資料、積分試算與志願分析。</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{districts.map(([code,label,areas]) => <a key={code} className="group rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-lg" href={`/it_hs/it_hs.html?district=${code}#schools`}><span className="text-xs font-bold text-[#13755e]">全區查詢</span><strong className="mt-2 block text-xl">{label}</strong><small className="block text-sm text-slate-500">{areas}</small><b className="mt-4 block text-sm text-[#2868d7]">查詢學校 →</b></a>)}</div></section>
    <section id="tools" className="bg-[#eff5ff] py-20"><div className="mx-auto w-[min(1160px,calc(100%-32px))]"><p className="text-xs font-extrabold tracking-[.16em] text-[#2868d7]">常用工具</p><h2 className="mt-3 text-4xl font-extrabold tracking-[-.05em]">現在，你想先完成哪一件事？</h2><div className="mt-8 grid gap-4 lg:grid-cols-3"><Tool title="學校查詢" tag="全區資料" body="依學校名稱、學制、縣市與行政區快速篩選。" href="#districts" primary/><Tool title="積分試算" tag="依區規則" body="輸入會考與多元表現，掌握免試入學積分。" href="#districts"/><Tool title="志願分析" tag="志願規劃" body="比對分數與學校資料，安排穩定、適中與挑戰志願。" href="#districts"/></div></div></section>
    <section id="pathways" className="mx-auto grid w-[min(1160px,calc(100%-32px))] gap-4 py-20 md:grid-cols-[1.4fr_.8fr]"><a className="rounded-3xl bg-gradient-to-br from-[#173d78] to-[#2868d7] p-8 text-white" href="/it_hs/it_hs.html#overview"><span className="text-xs font-bold tracking-[.14em] text-blue-200">高中職</span><h2 className="mt-4 text-3xl font-extrabold">高中、高職與綜合高中</h2><p className="mt-3 text-blue-100">三年制的學科、專業實作與彈性探索路徑。</p><b className="mt-12 block text-sm">比較學制 →</b></a><a className="rounded-3xl border border-slate-200 bg-white p-8" href="/it_5/it_5.html"><span className="text-xs font-bold tracking-[.14em] text-[#2868d7]">五專</span><h2 className="mt-4 text-3xl font-extrabold">五專</h2><p className="mt-3 text-slate-500">提早深入專業，五年完成中等與專科教育。</p><b className="mt-12 block text-sm text-[#2868d7]">前往五專專區 →</b></a></section>
    <footer className="border-t border-slate-200 bg-white py-8"><div className="mx-auto flex w-[min(1160px,calc(100%-32px))] flex-col justify-between gap-4 text-sm text-slate-500 md:flex-row"><b className="text-[#17233b]">全國國中升學資訊網</b><span>資料以各區免試入學委員會、教育部與學校公告為準。</span></div></footer>
  </main>;
}

function Tool({title,tag,body,href,primary=false}:{title:string;tag:string;body:string;href:string;primary?:boolean}) { return <a href={href} className={`min-h-64 rounded-3xl border p-7 ${primary ? "border-[#173d78] bg-[#173d78] text-white" : "border-slate-200 bg-white"}`}><p className={`text-xs font-bold ${primary ? "text-blue-200" : "text-slate-500"}`}>{tag}</p><h3 className="mt-3 text-2xl font-extrabold">{title}</h3><p className={`mt-3 text-sm leading-7 ${primary ? "text-blue-100" : "text-slate-500"}`}>{body}</p><b className={`mt-12 block text-sm ${primary ? "text-white" : "text-[#2868d7]"}`}>選擇就學區 →</b></a>}
