"use client";
import { useEffect, useState } from "react";
import type { MemberSession } from "@/lib/member-auth";
export function AccountCenter({ member, error, registered = false }: { member: MemberSession | null; error?: string; registered?: boolean }) {
  const [officialLineUrl, setOfficialLineUrl] = useState("");
  useEffect(() => { fetch("/api/site-config", { headers: { accept: "application/json" } }).then((response) => response.ok ? response.json() as Promise<{ official_line_url?: string }> : null).then((config) => { if (config?.official_line_url) setOfficialLineUrl(config.official_line_url); }).catch(() => undefined); }, []);
  const message = error === "line_friend_required" ? "請先加入官方 LINE 好友，再完成會員登入。" : error ? "LINE 登入尚未完成，請重新嘗試。" : "";
  return <section className="mx-auto w-[min(1160px,calc(100%-32px))] py-10"><div className="grid gap-4 md:grid-cols-2"><article className="p-6 jshs-surface-card"><p className="jshs-eyebrow">LINE 會員</p><h2 className="mt-2">{member ? `嗨，${member.displayName}` : "使用 LINE 註冊／登入"}</h2><p className="mt-3 text-sm leading-7 jshs-muted-copy">只有 LINE 會員資料會保存到本站 Cloudflare D1；未登入時輸入只保留在目前頁面，不會寫入本機。</p>{message ? <p role="alert" className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-950">{message}</p> : null}{registered ? <p className="mt-5 text-sm font-bold text-emerald-800" role="status">LINE 會員已完成登入。</p> : null}{member ? <form action="/api/line/logout" method="post"><button type="submit" className="mt-5 px-4 py-3 text-sm jshs-button-secondary">登出</button></form> : <a href="/api/line/login/start" className="mt-5 inline-flex px-4 py-3 text-sm jshs-button-primary">使用 LINE 註冊／登入</a>}</article><article className="p-6 jshs-surface-card"><p className="jshs-eyebrow">資料原則</p><h2 className="mt-2">你的資料只跟著會員帳號走</h2><p className="mt-3 text-sm leading-7 jshs-muted-copy">成績、模考、志願規劃與 AI 對話會依功能保存至 Learning D1；收藏、通知與會員設定保存至 Core D1。網站內容回報與管理資料則由 Community D1 管理。</p>{officialLineUrl ? <a href={officialLineUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex px-4 py-3 text-sm jshs-button-secondary">加入官方 LINE 好友</a> : null}</article></div></section>;
}
