"use client";

import Link from "next/link";
import { FormEvent, KeyboardEvent, useCallback, useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { AiChatMarkdown } from "./ai-chat-markdown";
import { appendMessage, ChatConversation, ChatMessage, createConversation, getAllConversations, getConversation, getCurrentConversationId, removeMessage, replaceMessage, setCurrentConversationId, updateConversation } from "../lib/ai-chat-storage";

type Source = Readonly<{ title: string; url: string; snippet?: string }>;
type Action = Readonly<{ label: string; href: string; reason: string }>;
type WorkspaceMode = "floating" | "full";
type ChatResult = { answer: string; sources: readonly Source[]; action?: Action; usage?: { remaining?: number | null }; intent?: string };
type StreamEvent = { delta?: string; meta?: Omit<ChatResult, "answer">; answer?: string; error?: string };
type ChatError = Error & { code?: string; status?: number };
type FailedRequest = { conversationId: string; question: string };
type ActiveRequest = { conversationId: string; requestId: string; assistantMessageId: string; controller: AbortController };

const suggestions = ["免試入學是什麼？", "中投區積分怎麼算？", "幫我寫一個 Python for loop", "幫我整理成表格"];
const isUsableHistoryMessage = (message: ChatMessage) => message.status !== "error" && !message.error;

function makeId() { return typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function makeMessage(conversationId: string, role: ChatMessage["role"], content: string, extra: Partial<ChatMessage> = {}): ChatMessage { return { id: makeId(), conversationId, role, content, createdAt: Date.now(), status: "complete", ...extra }; }
function logDebug(event: string, details: Record<string, string | number | undefined>) { if (process.env.NODE_ENV === "development") console.debug(`[AI ${event}]`, details); }

async function requestAssistant(question: string, history: readonly ChatMessage[], signal: AbortSignal, onDelta: (answer: string) => void): Promise<ChatResult> {
  const response = await fetch("/api/assistant", { method: "POST", headers: { "content-type": "application/json" }, signal, body: JSON.stringify({ question, stream: true, history: history.filter(isUsableHistoryMessage).slice(-6).map(({ role, content }) => ({ role, content: content.slice(0, 1200) })) }) });
  const contentType = response.headers.get("content-type") || "";
  if (!response.ok) { const body = await response.json().catch(() => null) as { error?: string } | null; const error = new Error("assistant_failed") as ChatError; error.code = body?.error; error.status = response.status; throw error; }
  if (!contentType.includes("text/event-stream") || !response.body) return await response.json() as ChatResult;
  const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; let answer = ""; let metadata: Omit<ChatResult, "answer"> = { sources: [] }; let completed = false;
  const parseEvent = (event: string) => { const data = event.split(/\r?\n/u).filter((line) => line.startsWith("data:")).map((line) => line.replace(/^data:\s?/u, "")).join("\n").trim(); if (!data || data === "[DONE]") { if (data === "[DONE]") completed = true; return; } let parsed: StreamEvent; try { parsed = JSON.parse(data) as StreamEvent; } catch { throw Object.assign(new Error("assistant_invalid_stream"), { code: "assistant_invalid_stream" }); } if (parsed.error) throw Object.assign(new Error("assistant_stream_failed"), { code: parsed.error }); if (parsed.meta) metadata = { ...metadata, ...parsed.meta }; if (parsed.delta) { answer += parsed.delta; onDelta(answer); } if (parsed.answer && !answer) { answer = parsed.answer; onDelta(answer); } };
  try { while (true) { const chunk = await reader.read(); buffer += decoder.decode(chunk.value || new Uint8Array(), { stream: !chunk.done }); const events = buffer.split(/\r?\n\r?\n/u); buffer = events.pop() || ""; events.forEach(parseEvent); if (chunk.done) break; } if (buffer.trim()) parseEvent(buffer); } finally { reader.releaseLock(); }
  if (!completed && !answer) throw Object.assign(new Error("assistant_stream_empty"), { code: "assistant_stream_empty" });
  return { answer, ...metadata };
}

function ErrorNotice({ error, onRetry }: { error: string; onRetry: () => void }) { return <div className="ai-chat-error" role="alert"><p>{error}</p><button type="button" onClick={onRetry}>重新產生</button></div>; }
function Message({ message }: { message: ChatMessage }) { return <article className={`ai-chat-message ${message.role === "user" ? "is-user" : "is-assistant"}`}>{message.role === "assistant" ? <div className="ai-chat-avatar" aria-hidden="true">✦</div> : null}<div className="ai-chat-message-body"><span className="ai-chat-message-label">{message.role === "assistant" ? "AI 小助手" : "你"}</span><AiChatMarkdown content={message.content} />{message.action ? <Link className="ai-chat-action" href={message.action.href}>{message.action.label} <span aria-hidden="true">↗</span></Link> : null}{message.sources?.length ? <div className="ai-chat-sources" aria-label="回答來源">{message.sources.map((source) => <a className="ai-chat-source-chip" key={source.url} href={source.url}>{source.title} <span aria-hidden="true">↗</span></a>)}</div> : null}</div></article>; }
function ChatInput({ value, loading, onChange, onSubmit }: { value: string; loading: boolean; onChange: (value: string) => void; onSubmit: () => void }) { const ref = useRef<HTMLTextAreaElement>(null); function resize() { if (!ref.current) return; ref.current.style.height = "auto"; ref.current.style.height = `${Math.min(ref.current.scrollHeight, 140)}px`; } function handleKeyDown(event: KeyboardEvent<HTMLTextAreaElement>) { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); onSubmit(); } } return <div className="ai-chat-composer"><textarea ref={ref} value={value} rows={1} maxLength={500} onChange={(event) => { onChange(event.target.value); resize(); }} onKeyDown={handleKeyDown} placeholder="問我升學問題，或任何你想問的事情…" aria-label="輸入訊息" disabled={loading} /><button type="button" aria-label="送出訊息" onClick={onSubmit} disabled={loading || value.trim().length < 2}>{loading ? <span className="ai-chat-spinner" aria-hidden="true" /> : "↑"}</button><small>Enter 送出 · Shift + Enter 換行</small></div>; }

function ChatWorkspace({ mode, onClose, initialConversationId = "" }: { mode: WorkspaceMode; onClose?: () => void; initialConversationId?: string }) {
  const [conversation, setConversation] = useState<ChatConversation | null>(null); const [conversations, setConversations] = useState<ChatConversation[]>([]); const [question, setQuestion] = useState(""); const [loading, setLoading] = useState(false); const [draftAnswer, setDraftAnswer] = useState(""); const [failedRequest, setFailedRequest] = useState<FailedRequest | null>(null); const [error, setError] = useState("");
  const activeRequestRef = useRef<ActiveRequest | null>(null); const conversationRef = useRef<ChatConversation | null>(null); const messagesRef = useRef<HTMLDivElement>(null);
  const setActiveConversation = useCallback((next: ChatConversation | null) => { conversationRef.current = next; setConversation(next); }, []);
  const abortActive = useCallback(() => { const active = activeRequestRef.current; if (!active) return; active.controller.abort(); logDebug("Request Abort", { conversationId: active.conversationId, requestId: active.requestId }); activeRequestRef.current = null; setLoading(false); setDraftAnswer(""); }, []);
  const persist = useCallback(async (next: ChatConversation) => { setActiveConversation(next); await updateConversation(next); setConversations((items) => [next, ...items.filter((item) => item.id !== next.id)].sort((a, b) => b.updatedAt - a.updatedAt)); }, [setActiveConversation]);
  useEffect(() => { let cancelled = false; const timer = window.setTimeout(() => { void (async () => { const all = await getAllConversations(); const current = initialConversationId || getCurrentConversationId(); const selected = (current && await getConversation(current)) || all[0] || await createConversation(); if (!cancelled) { setConversations(all); setActiveConversation(selected); setCurrentConversationId(selected.id); } })(); }, 0); return () => { cancelled = true; window.clearTimeout(timer); abortActive(); }; }, [abortActive, initialConversationId, setActiveConversation]);
  useEffect(() => { const container = messagesRef.current; if (!container) return; container.scrollTo({ top: container.scrollHeight, behavior: loading ? "auto" : "smooth" }); }, [conversation?.messages.length, draftAnswer, loading, error]);
  async function select(next: ChatConversation) { abortActive(); setFailedRequest(null); setError(""); setActiveConversation(next); setCurrentConversationId(next.id); }
  async function newConversation() { abortActive(); setFailedRequest(null); setError(""); const next = await createConversation(); setActiveConversation(next); setConversations((items) => [next, ...items]); }
  async function generate(text: string, base: ChatConversation, isRetry = false) {
    if (activeRequestRef.current || text.length < 2) return; const requestId = makeId(); const controller = new AbortController(); const userMessage = isRetry ? null : makeMessage(base.id, "user", text); const requestBase = userMessage ? appendMessage(base, userMessage) : base; const assistantMessage = makeMessage(base.id, "assistant", "", { status: "pending" }); const optimistic = appendMessage(requestBase, assistantMessage); const historySource = isRetry && base.messages.at(-1)?.role === "user" && base.messages.at(-1)?.content === text ? base.messages.slice(0, -1) : base.messages; const historySnapshot = historySource.filter(isUsableHistoryMessage).slice(-6); // Keep the current question out of history; the API appends it once (history.slice(-6)).
    activeRequestRef.current = { conversationId: base.id, requestId, assistantMessageId: assistantMessage.id, controller }; setActiveConversation(optimistic); setLoading(true); setDraftAnswer(""); setError(""); setFailedRequest(null); logDebug("Request Start", { conversationId: base.id, requestId });
    try { const result = await requestAssistant(text, historySnapshot, controller.signal, (answer) => { const active = activeRequestRef.current; if (!active || active.requestId !== requestId || conversationRef.current?.id !== base.id) return; setDraftAnswer(answer); setConversation((current) => current && current.id === base.id ? replaceMessage(current, { ...assistantMessage, content: answer, status: "streaming" }) : current); }); const active = activeRequestRef.current; if (!active || active.requestId !== requestId || conversationRef.current?.id !== base.id) return; const complete = { ...assistantMessage, content: result.answer, status: "complete" as const, sources: result.sources, action: result.action }; const finished = replaceMessage(conversationRef.current || optimistic, complete); activeRequestRef.current = null; setDraftAnswer(""); setLoading(false); logDebug("Request Complete", { conversationId: base.id, requestId }); await persist(finished); } catch (cause) { const active = activeRequestRef.current; if ((cause as DOMException).name === "AbortError" || !active || active.requestId !== requestId) return; activeRequestRef.current = null; setLoading(false); setDraftAnswer(""); const cleaned = removeMessage(conversationRef.current || optimistic, assistantMessage.id); if (conversationRef.current?.id === base.id) { setActiveConversation(cleaned); setFailedRequest({ conversationId: base.id, question: text }); setError(toUserError(cause as ChatError)); } await updateConversation(cleaned); logDebug("Request Error", { conversationId: base.id, requestId, status: (cause as ChatError).status }); }
  }
  async function submit(event?: FormEvent, retryQuestion?: string) { event?.preventDefault(); const text = (retryQuestion ?? question).trim(); if (loading || text.length < 2 || !conversation) return; if (!retryQuestion) setQuestion(""); await generate(text, conversation, Boolean(retryQuestion)); }
  const retry = () => { if (!failedRequest || !conversation || failedRequest.conversationId !== conversation.id || loading) return; void generate(failedRequest.question, conversation, true); };
  return <section className={`ai-chat-window ai-chat-${mode}`} aria-label="AI 小助手">{mode === "full" ? <aside className="ai-chat-sidebar" aria-label="本機對話"><div className="ai-chat-sidebar-head"><strong>本機對話</strong><button type="button" onClick={newConversation}>＋ 新對話</button></div><div className="ai-chat-conversation-list">{conversations.map((item) => <button key={item.id} type="button" className={item.id === conversation?.id ? "is-active" : ""} onClick={() => void select(item)}>{item.title}</button>)}</div><p>對話只儲存在這台裝置的 IndexedDB，不會上傳雲端。</p></aside> : null}<div className="ai-chat-main"><header className="ai-chat-header"><div className="ai-chat-brand"><span className="ai-chat-logo" aria-hidden="true">✦</span><div><strong>AI 小助手</strong><small>一般 AI · 升學資料助手</small></div></div><div className="ai-chat-header-actions">{mode === "floating" ? <Link href={`/ai${conversation ? `?conversation=${conversation.id}` : ""}`} aria-label="開啟完整對話" title="開啟完整對話">↗</Link> : null}{onClose ? <button type="button" onClick={onClose} aria-label="關閉 AI 小助手" title="關閉">×</button> : null}</div></header>{mode === "floating" ? <p className="ai-chat-scope">可以聊任何問題；遇到本站升學資料時會優先查找網站內容。</p> : null}<div className="ai-chat-body"><div ref={messagesRef} className="ai-chat-messages"><div className="ai-chat-message-column">{conversation?.messages.length ? conversation.messages.filter((message) => isUsableHistoryMessage(message) && message.status !== "pending" && message.status !== "streaming").map((message) => <Message key={message.id} message={message} />) : <div className="ai-chat-empty"><span className="ai-chat-empty-logo" aria-hidden="true">✦</span><h2>你好，我是 AI 小助手</h2><p>可以問升學、學習、程式，或任何你想聊的事情。</p><div className="ai-chat-suggestions">{suggestions.map((item) => <button key={item} type="button" onClick={() => setQuestion(item)}>{item}</button>)}</div></div>}{loading ? <article className="ai-chat-message is-assistant"><div className="ai-chat-avatar" aria-hidden="true">✦</div><div className="ai-chat-message-body"><span className="ai-chat-message-label">AI 小助手</span>{draftAnswer ? <AiChatMarkdown content={draftAnswer} /> : <span className="ai-chat-dots" aria-label="AI 正在思考"><i /> <i /> <i /></span>}</div></article> : null}{error && failedRequest ? <ErrorNotice error={error} onRetry={retry} /> : null}</div></div></div><form onSubmit={submit}><ChatInput value={question} loading={loading} onChange={setQuestion} onSubmit={() => void submit()} /></form></div></section>;
}
function toUserError(error: ChatError) { if (error.code === "guest_limit_reached") return "訪客免費提問次數已用完，登入 LINE 會員後即可繼續使用。"; if (error.status === 429 || error.code === "assistant_rate_limited") return "目前 AI 使用量較高，請稍後再試。"; if (error.code === "assistant_timeout") return "AI 回應時間較久，請再試一次。"; if (error.code === "assistant_stream_failed" || error.code === "assistant_invalid_stream" || error.code === "assistant_stream_empty") return "AI 回覆中斷，請重新產生。"; if (error.status && error.status >= 400 && error.status < 500) return "這個問題目前無法送出，請稍微修改後再試。"; return "AI 暫時沒有成功回應，請再試一次。"; }
// The floating shell itself is position: fixed near the bottom/right; its internal chat layout stays in normal flex flow.
export function AiAssistant() { const pathname = usePathname(); const [open, setOpen] = useState(false); if (pathname === "/ai") return null; return <div className="ai-chat-root">{open ? <ChatWorkspace mode="floating" onClose={() => setOpen(false)} /> : null}{!open ? <button type="button" className="ai-chat-floating-button" aria-label="開啟 AI 小助手" aria-expanded={false} onClick={() => setOpen(true)}><span aria-hidden="true">✦</span><span className="ai-chat-floating-label">AI 小助手</span></button> : null}</div>; }
export function AiChatPage({ initialConversationId = "" }: { initialConversationId?: string }) { return <main className="ai-chat-page"><ChatWorkspace mode="full" initialConversationId={initialConversationId} /></main>; }
