"use client";
import Link from "next/link";
import { useState } from "react";
import type { School } from "@/lib/school-repository";
import { SchoolSelection } from "@/components/school-selection";

export function CommuteComparison({ schools, initialDistrict }: { schools: readonly School[]; initialDistrict?: string }) {
  const [selected, setSelected] = useState<readonly string[]>([]);
  const [origin, setOrigin] = useState("");
  const chosen = schools.filter(s => selected.includes(s.code));
  return <section className="mx-auto w-[min(1180px,calc(100%-32px))] py-8"><SchoolSelection schools={schools} selected={selected} initialDistrict={initialDistrict} onToggle={code => setSelected(current => current.includes(code) ? current.filter(c => c !== code) : current.length < 4 ? [...current, code] : current)} /><label className="mt-6 grid gap-2 rounded-xl border p-5">你的路線出發地<input className="min-h-11 w-full min-w-0" value={origin} onChange={e => setOrigin(e.target.value)} placeholder="例如：臺中車站" maxLength={240} /><span className="text-sm">點擊路線試算後，出發地將交由 Google 地圖計算；本站不保存出發地。</span></label><div className="mt-6 grid gap-4 md:grid-cols-2">{chosen.map(s => <article className="min-w-0 rounded-2xl border p-5" key={s.code}><h2 className="text-xl font-bold">{s.name}</h2><p className="mt-2">{s.schoolType} · {s.city} {s.area}</p><section className="mt-5"><h3 className="font-bold">校方交通資訊</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7">{s.transport || '目前沒有資料'}</p><h4 className="mt-4 font-bold">通勤說明</h4><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7">{s.commute || '目前沒有資料'}</p>{s.sources.transport.map((source, i) => <a key={`${source.url}:${i}`} className="inline-flex min-h-11 items-center text-sm text-blue-700" href={source.url} target="_blank" rel="noreferrer">官方交通來源 {i + 1} ↗</a>)}</section><section className="mt-5 rounded-xl bg-blue-50 p-4"><h3 className="font-bold">你的路線試算</h3><p className="mt-2 text-sm leading-7">第三方路線計算在 Google 地圖開啟，可選擇大眾運輸或開車。本站目前不顯示即時計算的距離與時間；校方資訊不代表你的實際通勤時間。</p>{origin.trim() && s.address ? <a className="mt-3 inline-flex min-h-11 items-center text-blue-700" href={`https://www.google.com/maps/dir/?${new URLSearchParams({ api: '1', origin: origin.trim(), destination: `${s.name} ${s.address}` }).toString()}`} target="_blank" rel="noreferrer">Google 地圖路線試算 ↗</a> : <p className="mt-3 text-sm">{s.address ? '輸入出發地後可開啟路線試算。' : '目前沒有學校地址，暫時無法建立路線。'}</p>}</section><Link className="mt-3 inline-flex min-h-11 items-center text-blue-700" href={`/schools/${s.code}`}>查看學校與住宿資訊 →</Link></article>)}</div>{!chosen.length ? <p className="mt-5">加入學校後，比較各校公開的交通與通勤說明。</p> : null}</section>;
}
