import Link from "next/link";

type Article = { title: string; summary: string; category: string; academicYear: string; districts: readonly string[]; publishedAt: string; updatedAt: string; lastCheckedAt: string; body: string; sections: readonly string[][]; relatedTools: readonly string[][]; sources: readonly { label: string; url: string; note?: string }[] };

export function GuideArticleDetail({ article }: { article: Article }) {
  return <section className="mx-auto w-[min(960px,calc(100%-32px))] py-10"><Link href="/knowledge" className="text-sm font-black text-[var(--jshs-primary)]">← 回到升學知識中心</Link><article className="mt-5 p-7 jshs-surface-card md:p-10"><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-[var(--jshs-brand-tint)] px-3 py-1 font-black text-[var(--jshs-primary)]">{article.category}</span><span className="rounded-full bg-[var(--jshs-muted-surface)] px-3 py-1">{article.academicYear} 學年度 · {article.districts.join("、")}</span></div><h1 className="mt-5 text-3xl md:text-4xl">{article.title}</h1><p className="mt-4 text-base leading-8 jshs-muted-copy">{article.summary}</p><button type="button" className="mt-5 px-4 py-3 text-sm jshs-button-primary" onClick={() => openAi(`我正在閱讀「${article.title}」，請用國中生聽得懂的方式解釋重點，並告訴我下一步。`)}>請 AI 用白話解釋 →</button><div className="mt-8 rounded-2xl bg-[var(--jshs-muted-surface)] p-5 text-sm leading-7">{article.body}</div><div className="mt-8 grid gap-4 md:grid-cols-3">{article.sections.map(([title, body]) => <section key={title} className="rounded-2xl border border-[var(--jshs-border)] p-5"><h2 className="text-lg">{title}</h2><p className="mt-2 text-sm leading-7 jshs-muted-copy">{body}</p></section>)}</div><section className="mt-9"><h2 className="text-xl">接著可以做什麼</h2><div className="mt-3 flex flex-wrap gap-3">{article.relatedTools.map(([label, href]) => <Link key={href} href={href} className="px-4 py-3 text-sm jshs-button-secondary">{label} →</Link>)}</div></section><section className="mt-9 border-t border-[var(--jshs-border)] pt-6"><h2 className="text-xl">原始來源與資料狀態</h2><p className="mt-2 text-sm leading-7 jshs-muted-copy">發布：{article.publishedAt} · 更新：{article.updatedAt} · 最後核對：{article.lastCheckedAt}</p><ul className="mt-3 grid gap-3">{article.sources.map((source) => <li key={source.url} className="text-sm"><a className="font-black text-[var(--jshs-primary)] underline" href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a>{source.note ? <span className="ml-2 jshs-muted-copy">{source.note}</span> : null}</li>)}</ul></section></article></section>;
}

function openAi(question: string) { document.dispatchEvent(new CustomEvent("jshs:ai-context", { detail: { question } })); }
