"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

export type Topic = "admission-basics" | "glossary" | "misconceptions" | "alumni-stories" | "videos" | "podcast" | "fit-quiz" | "career-map" | "groups";
const terms = [["超額比序", "當申請人數超過名額時，依招生區公告的項目與順序比較。"], ["序位", "依同區規則與資料產生的排序位置，本站試算不等於正式序位。"], ["免試入學", "依就學區規則、成績與志願選填辦理的入學管道。"], ["志願序", "你填寫學校或校科的先後順序，實際計分依各區規則。"], ["群科", "技術型高中把相近的專業學習內容整理成群科。"], ["五專", "五年制專科學校，完成後取得副學士學位。"]] as const;
const misconceptions = [["分數越高就一定能錄取", "不一定。名額、志願序、同分比序與資格審查都可能影響結果。"], ["歷年最低分就是今年門檻", "不是。歷年資料只能參考，不能當成今年錄取保證。"], ["技高只適合不想讀書的人", "不是。技高有完整的專業課程、實作與升學路徑。"]] as const;
const stories = [["課程", "喜歡動手做的學生", "先看實習工場與課程內容，再比較通勤與未來升學。"], ["通勤", "每天通勤一小時的家庭", "把最晚回家時間、交通轉乘與雨天備案一起列入比較。"], ["選擇", "在普高與技高間猶豫", "先保留兩種路徑各一組候選，再用課程與學習方式逐步縮小。"]] as const;
const media = [["就學區", "90 秒理解就學區怎麼影響選校", "先確認你適用的區域，再看該區規則與學校。", "/media/admission-basics.m4a"], ["志願", "2 分鐘看懂挑戰、穩定、保底", "三層是溝通與整理工具，不是錄取保證。", "/media/volunteer-strategy.m4a"], ["校科", "3 分鐘認識群科與課程", "從學習內容出發，比只看校名更容易找到適合方向。", "/media/school-comparison.m4a"]] as const;
const videoUrl = "https://www.youtube.com/watch?v=ngAfGvBO_7A";
const videoEmbedUrl = "https://www.youtube.com/embed/ngAfGvBO_7A";
const pathways = [["普通高中", "重視學科基礎與升學準備", "大學學系、學術研究、跨領域探索"], ["技術型高中", "專業群科、實作與證照", "科技大學、技專校院、產學與就業"], ["五專", "五年制專業學習", "副學士、二技、專業職涯"]] as const;

export function KnowledgeTopicWorkspace({ topic }: { topic: Topic }) {
  const page = { "admission-basics": ["3 分鐘看懂免試入學", "用四個步驟掌握從區域到志願的決策順序。"], glossary: ["名詞小百科", "搜尋升學常見詞彙，點開查看簡明解釋。"], misconceptions: ["常見迷思破解", "選出你的判斷，立即看見為什麼需要再核對。"], "alumni-stories": ["過來人經驗談", "依主題閱讀整理過的學習與選校經驗。"], videos: ["升學短影音系列", "選擇主題查看重點與文字摘要。"], podcast: ["升學 Podcast／語音版", "用短集數掌握概念，展開文字重點。"], "fit-quiz": ["學制適合度測驗", "回答三題，整理目前較適合優先比較的學制。"], "career-map": ["未來銜接大學科系地圖", "點選學制，查看可能的後續方向。"], groups: ["群科／十五群科介紹", "從學習內容與未來方向認識技術型高中群科。"] }[topic];
  return <section className="mx-auto w-[min(1120px,calc(100%-32px))] py-10"><div className="mb-6"><p className="jshs-eyebrow">升學知識 · 可操作工具</p><h1 className="mt-2">{page[0]}</h1><p className="mt-3 max-w-3xl text-base leading-7 jshs-muted-copy">{page[1]}</p></div>{topic === "admission-basics" ? <Basics /> : topic === "glossary" ? <Glossary /> : topic === "misconceptions" ? <Misconceptions /> : topic === "alumni-stories" ? <StoryList /> : topic === "videos" || topic === "podcast" ? <MediaList kind={topic} /> : topic === "fit-quiz" ? <FitQuiz /> : <CareerMap groups={topic === "groups" ? pathways.slice(1) : pathways} />}</section>;
}
function Basics() { const steps = [["確認就學區", "就學區決定適用規則、日期與可填範圍。", "/districts"], ["完成成績試算", "先輸入會考與必要資料，取得自己的分數依據。", "/tools"], ["查詢校科", "比較課程、群科、通勤、名額與歷年參考。", "/schools"], ["整理志願", "選擇系統推薦或自選排序，建立願意就讀的清單。", "/planner"]] as const; const [active, setActive] = useState(0); return <div className="grid gap-4 md:grid-cols-[280px_1fr]"><nav className="grid gap-2">{steps.map(([title], index) => <button key={title} type="button" onClick={() => setActive(index)} className={`p-4 text-left text-sm jshs-button ${active === index ? "jshs-button-primary" : "jshs-button-secondary"}`}>{index + 1}. {title}</button>)}</nav><article className="p-6 jshs-surface-card"><p className="jshs-eyebrow">第 {active + 1} 步</p><h2 className="mt-2">{steps[active][0]}</h2><p className="mt-3 text-sm leading-7 jshs-muted-copy">{steps[active][1]}</p><Link href={steps[active][2]} className="mt-5 inline-flex px-4 py-3 text-sm jshs-button-primary">前往操作 →</Link></article></div>; }
function Glossary() { const [query, setQuery] = useState(""); const matches = useMemo(() => terms.filter(([title, body]) => `${title}${body}`.includes(query.trim())), [query]); return <div className="p-6 jshs-surface-card"><label className="grid gap-2 text-sm font-black">搜尋名詞<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="例如：序位、群科、志願" /></label><div className="mt-5 grid gap-3">{matches.map(([title, body]) => <details key={title} className="rounded-2xl bg-[var(--jshs-muted-surface)] p-4"><summary className="cursor-pointer font-black text-[var(--jshs-primary)]">{title}</summary><p className="mt-2 text-sm leading-7 jshs-muted-copy">{body}</p></details>)}{!matches.length ? <p className="text-sm jshs-muted-copy">找不到詞，請換個關鍵字。</p> : null}</div></div>; }
function Misconceptions() { const [selected, setSelected] = useState<number | null>(null); return <div className="grid gap-3">{misconceptions.map(([claim, answer], index) => <article key={claim} className="p-5 jshs-surface-card"><h2 className="text-lg">{claim}</h2><button type="button" onClick={() => setSelected(selected === index ? null : index)} className="mt-4 px-4 py-3 text-sm jshs-button-secondary">{selected === index ? "收起判斷" : "查看判斷"}</button>{selected === index ? <p className="mt-4 rounded-2xl bg-[var(--jshs-brand-tint)] p-4 text-sm leading-7 text-[var(--jshs-primary)]">{answer}</p> : null}</article>)}</div>; }
function StoryList() { const [filter, setFilter] = useState("全部"); const list = filter === "全部" ? stories : stories.filter(([tag]) => tag === filter); return <><div className="flex flex-wrap gap-2">{["全部", "課程", "通勤", "選擇"].map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`px-3 py-2 text-sm jshs-button ${filter === item ? "jshs-button-primary" : "jshs-button-secondary"}`}>{item}</button>)}</div><div className="mt-4 grid gap-4 md:grid-cols-3">{list.map(([tag, title, body]) => <article key={title} className="p-5 jshs-surface-card"><span className="jshs-chip">{tag}</span><h2 className="mt-3 text-lg">{title}</h2><p className="mt-2 text-sm leading-7 jshs-muted-copy">{body}</p></article>)}</div></>; }
function MediaList({ kind }: { kind: "videos" | "podcast" }) { return <div className="grid gap-4 md:grid-cols-3">{media.map(([tag, title, body, audioSrc], index) => <article key={title} className="p-5 jshs-surface-card"><span className="jshs-chip">{kind === "videos" ? "影片重點" : "語音短集"} · {tag}</span><h2 className="mt-3 text-lg">{title}</h2>{kind === "videos" ? index === 0 ? <div className="mt-4 overflow-hidden rounded-2xl bg-black"><iframe className="aspect-video w-full" src={videoEmbedUrl} title={title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div> : <a className="mt-4 inline-flex px-4 py-3 text-sm jshs-button-primary" href={videoUrl} target="_blank" rel="noreferrer">在 YouTube 播放 →</a> : <audio className="mt-4 w-full" controls preload="metadata" src={audioSrc}>你的瀏覽器不支援音訊播放。</audio>}<p className="mt-4 text-sm leading-7 jshs-muted-copy">{body} 建議看完後接著前往相關工具，把理解轉成自己的下一步。</p></article>)}</div>; }
function FitQuiz() { const [answers, setAnswers] = useState<string[]>([]); const options = [["我喜歡理解原理與閱讀", "普通高中"], ["我喜歡實作與完成作品", "技術型高中"], ["我想保留兩種方向", "綜合高中／比較三種學制"]] as const; const choose = (index: number, value: string) => setAnswers((current) => { const next = [...current]; next[index] = value; return next; }); const completed = answers.filter(Boolean).length === 3; const result = completed ? [...answers].sort((a, b) => answers.filter((x) => x === b).length - answers.filter((x) => x === a).length)[0] : ""; return <div className="p-6 jshs-surface-card"><div className="grid gap-4">{["平常最有興趣的學習方式？", "你希望先專注哪種內容？", "你對未來方向的想法？"].map((question, index) => <fieldset key={question}><legend className="text-sm font-black">{index + 1}. {question}</legend><div className="mt-2 grid gap-2">{options.map(([label, value]) => <button key={`${index}-${label}`} type="button" onClick={() => choose(index, value)} className={`p-3 text-left text-sm jshs-button ${answers[index] === value ? "jshs-button-primary" : "jshs-button-secondary"}`}>{label}</button>)}</div></fieldset>)}</div>{result ? <p className="mt-5 rounded-2xl bg-[var(--jshs-brand-tint)] p-4 text-sm leading-7 text-[var(--jshs-primary)]">目前結果：優先比較「{result}」。這不是錄取判定，請再用課程與學校資料驗證。</p> : <p className="mt-5 text-sm jshs-muted-copy">請完成三題，系統會整理你的優先比較方向。</p>}</div>; }
function CareerMap({ groups }: { groups: readonly (readonly [string, string, string])[] }) { const [active, setActive] = useState(0); return <div className="grid gap-4 md:grid-cols-[260px_1fr]"><nav className="grid gap-2">{groups.map(([title], index) => <button key={title} type="button" onClick={() => setActive(index)} className={`p-4 text-left text-sm jshs-button ${active === index ? "jshs-button-primary" : "jshs-button-secondary"}`}>{title}</button>)}</nav><article className="p-6 jshs-surface-card"><h2>{groups[active][0]}</h2><p className="mt-3 text-sm leading-7 jshs-muted-copy">{groups[active][1]}</p><div className="mt-5 rounded-2xl bg-[var(--jshs-muted-surface)] p-4"><strong>可能方向</strong><p className="mt-2 text-sm leading-7 jshs-muted-copy">{groups[active][2]}</p></div><Link href="/schools" className="mt-5 inline-flex px-4 py-3 text-sm jshs-button-primary">用學校資料驗證 →</Link></article></div>; }
