"use client";

import { useEffect, useMemo, useState } from "react";

type MockRecord = { id: string; name: string; date: string; subjects: Record<string, number | null>; essay: string; createdAt: string };
const KEY = "jshs_mock_exam_records";
const subjects = ["國文", "數學", "英文", "社會", "自然"];

export function MockExamWorkspace({ mode = "manage", isMember = false }: { mode?: "manage" | "trends"; isMember?: boolean }) {
  const [records, setRecords] = useState<MockRecord[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState("");
  const [form, setForm] = useState({ name: "", date: new Date().toISOString().slice(0, 10), subjects: Object.fromEntries(subjects.map((s) => [s, ""])) as Record<string, string>, essay: "" });
  useEffect(() => { const timer = window.setTimeout(async () => { try { const parsed = JSON.parse(localStorage.getItem(KEY) || "[]"); const localRecords = Array.isArray(parsed) ? parsed : []; if (!isMember) setRecords(localRecords); else { const response = await fetch("/api/mock-exams", { headers: { accept: "application/json" } }); if (!response.ok) throw new Error("sync"); const payload = await response.json() as { records?: MockRecord[] }; setRecords(payload.records || localRecords); } } catch { setError(isMember ? "會員模考紀錄同步失敗，請重試。" : "讀取本機模考紀錄失敗，請重試。"); } finally { setLoaded(true); } }, 0); return () => window.clearTimeout(timer); }, [isMember]);
  const persist = async (next: MockRecord[]) => { setRecords(next); try { localStorage.setItem(KEY, JSON.stringify(next)); if (isMember) { for (const record of next) await fetch("/api/mock-exams", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(record) }); } setError(""); } catch { setError(isMember ? "保存或同步失敗，請稍後重試。" : "保存失敗，請檢查瀏覽器儲存空間後重試。"); } };
  const trend = useMemo(() => subjects.map((subject) => { const values = records.map((r) => r.subjects[subject]).filter((v): v is number => typeof v === "number"); return { subject, values, latest: values.at(-1), best: values.length ? Math.max(...values) : undefined, delta: values.length > 1 ? values.at(-1)! - values.at(-2)! : undefined }; }), [records]);
  if (!loaded) return <section className="jshs-state-card"><h2>載入模考紀錄中</h2></section>;
  if (mode === "trends") return <section className="mx-auto w-[min(1120px,calc(100%-32px))] py-10"><div className="jshs-surface-card p-6"><h2>科目趨勢與待加強</h2>{records.length < 2 ? <p className="mt-3 jshs-muted-copy">{records.length === 0 ? "尚無紀錄，新增至少兩次模考後才能分析。" : "目前只有一筆資料，先保存下一次模考才能比較變化。"}</p> : <div className="mt-4 grid gap-3 sm:grid-cols-2">{trend.map((item) => <article key={item.subject} className="rounded-xl bg-[var(--jshs-muted-surface)] p-4"><strong>{item.subject}</strong><p className="mt-2 text-sm">最新 {item.latest ?? "尚未提供"} · 最高 {item.best ?? "尚未提供"}</p><p className="mt-1 text-sm">近期變化：{item.delta === undefined ? "資料不足" : `${item.delta > 0 ? "+" : ""}${item.delta}`}</p></article>)}</div>}</div><p className="mt-4 text-sm jshs-muted-copy">分析只使用你保存的五科分數，不推測逐題錯誤、排名或章節弱點。</p></section>;
  const submit = (event: React.FormEvent) => { event.preventDefault(); const parsed = Object.fromEntries(subjects.map((s) => [s, form.subjects[s] === "" ? null : Number(form.subjects[s])])) as Record<string, number | null>; if (!form.name.trim() || !form.date || Object.values(parsed).some((v) => v !== null && (!Number.isFinite(v) || v < 0))) { setError("請填寫考試名稱、日期與正確的科目分數。"); return; } persist([{ id: crypto.randomUUID(), name: form.name.trim(), date: form.date, subjects: parsed, essay: form.essay.trim(), createdAt: new Date().toISOString() }, ...records]); setForm({ name: "", date: new Date().toISOString().slice(0, 10), subjects: Object.fromEntries(subjects.map((s) => [s, ""])) as Record<string, string>, essay: "" }); };
  return <section className="mx-auto w-[min(1120px,calc(100%-32px))] py-10"><div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><form onSubmit={submit} className="jshs-surface-card grid gap-3 p-6"><h2>建立模擬考紀錄</h2><input aria-label="考試名稱" placeholder="考試名稱" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input aria-label="考試日期" type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} />{subjects.map((subject) => <input key={subject} aria-label={`${subject}成績`} type="number" min="0" max="100" placeholder={`${subject}分數（可留白）`} value={form.subjects[subject]} onChange={(e) => setForm({ ...form, subjects: { ...form.subjects, [subject]: e.target.value } })} />)}<input aria-label="作文成績" type="text" placeholder="作文級分（可留白）" value={form.essay} onChange={(e) => setForm({ ...form, essay: e.target.value })} /><button className="jshs-button-primary" type="submit">保存模考</button>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<p className="text-xs jshs-muted-copy">未登入時保存於本機；不會產生答案、排名或錄取預測。</p></form><div className="jshs-surface-card p-6"><div className="flex items-center justify-between"><h2>歷次紀錄</h2><button type="button" className="text-sm text-red-700" onClick={() => persist([])}>清除全部</button></div>{!records.length ? <p className="mt-4 jshs-muted-copy">尚無紀錄，先建立一次模擬考。</p> : <div className="mt-4 grid gap-3">{records.map((record) => <article key={record.id} className="rounded-xl bg-[var(--jshs-muted-surface)] p-4"><div className="flex justify-between gap-3"><strong>{record.name}</strong><time>{record.date}</time></div><p className="mt-2 text-sm">{subjects.map((s) => `${s} ${record.subjects[s] ?? "未提供"}`).join(" · ")}</p><button type="button" className="mt-2 text-sm text-red-700" onClick={() => persist(records.filter((item) => item.id !== record.id))}>刪除</button></article>)}</div>}</div></div></section>;
}
