import data from '../content/schools/generated/schools.json';
import metadata from '../content/schools/generated/metadata.json';
import { searchSchoolRecords } from './school-data/pipeline.mjs';
export type InformationStatus = 'confirmed' | 'not_offered' | 'not_published' | 'not_applicable' | 'unclear';
export type SourceLink = {url:string;label:string};
export type SchoolDepartment = {name:string;quota:number|null;gender:string;raw:string};
export type AdmissionRecord = {id:string;sourceDistrict:string;admissionDistrict:string;admissionOfferingType:string;departmentRaw:string;departments:SchoolDepartment[];brochureQuota:string;admissionQuota:string;raw:Record<string,string>};
export type School = {code:string;name:string;ownership:string;admissionDistrict:string;admissionDistricts:string[];schoolType:string;gender:string;city:string;area:string;address:string;website:string;phone:string;departmentRaw:string;departments:SchoolDepartment[];brochureQuota:string;admissionQuota:string;scoreNote:string;features:string;courseDirection:string;project:string;transport:string;commute:string;lodging:string;mapUrl:string;sources:Record<'address'|'transport'|'lodging'|'course'|'project'|'life',SourceLink[]>;lodgingStatus:InformationStatus;transportStatus:InformationStatus;hasSchoolBus:boolean;hasPublicTransport:boolean;academicYear:string;raw:Record<string,string>;admissionRecords:AdmissionRecord[]; /** legacy admission-tool compatibility only; entity identity remains code */ districtCode?:string};
/** The discovery view deliberately excludes raw rows and source ledgers. */
export type SchoolSummary = Pick<School, 'code'|'name'|'ownership'|'admissionDistricts'|'schoolType'|'gender'|'city'|'area'|'departmentRaw'|'departments'|'admissionQuota'|'features'|'courseDirection'|'project'|'lodgingStatus'|'transportStatus'|'hasSchoolBus'|'hasPublicTransport'>;
export type SchoolEntity = School;
export type SchoolSearchFilters = {city?:string;area?:string;ownership?:string;schoolType?:string;gender?:string;admissionDistrict?:string;department?:string;lodging?:boolean;schoolBus?:boolean;publicTransport?:boolean};
const schools = data as School[];
const byCode = new Map(schools.map(s=>[s.code,s]));
export const getSchools = (): School[] => schools;
export const getSchoolSummaries = (): SchoolSummary[] => schools.map(({ raw, admissionRecords, sources, address, website, phone, brochureQuota, scoreNote, transport, commute, lodging, mapUrl, academicYear, admissionDistrict, ...summary }) => summary);
export const getSchoolByCode = (code:string):School|undefined => byCode.get(code);
export const searchSchools = (query='',filters:SchoolSearchFilters={}):School[] => searchSchoolRecords(schools,query,filters);
export const schoolMetadata = metadata;
export const schoolFilters = {cities:[...new Set(schools.map(s=>s.city))].sort(),districts:[...new Set(schools.flatMap(s=>s.admissionDistricts))].sort(),departments:[...new Set(schools.flatMap(s=>s.departments.map(d=>d.name)))].sort(),schoolTypes:['高中','高職','綜高','進修部'],genders:['男校','女校','男女校'],ownerships:['公立','私立']};
export const schoolRepository = {getSchools,getSchoolSummaries,getSchoolByCode,searchSchools};
export { renderField } from './school-data/pipeline.mjs';
