import districtMetadata from "../public/it_hs/district-metadata.json";
import { sourceRegistry, type CapabilityStatus, type SourceRegistryRecord } from "@/lib/source-registry";

export type { CapabilityStatus, SourceRegistryRecord } from "@/lib/source-registry";
export { sourceRegistry } from "@/lib/source-registry";
export type CapabilityRow = Readonly<{ district: string; label: string; admissionRules: CapabilityStatus; schoolDirectory: CapabilityStatus; admissionHistory: CapabilityStatus; schedule: CapabilityStatus; map: CapabilityStatus; planner: CapabilityStatus; sourceYear: string; lastVerifiedAt: string; reasons: Readonly<Record<string, string>> }>;
function sourceStatus(district: string, dataset: string): CapabilityStatus { const values = sourceRegistry.filter((source) => source.dataset === dataset && (source.district === district || source.district === "all")); return (["VERIFIED", "AVAILABLE", "PARTIAL", "PENDING", "UNAVAILABLE"] as const).find((status) => values.some((source) => source.status === status && (status !== "VERIFIED" || source.sourceType !== "community"))) || "UNAVAILABLE"; }
export function deriveDistrictCapability(district: string): Omit<CapabilityRow, "district" | "label" | "reasons"> { const value = districtMetadata.districts[district as keyof typeof districtMetadata.districts]; const sources = sourceRegistry.filter((source) => source.district === district || source.district === "all"); return { admissionRules: sourceStatus(district, "admission_rules"), schoolDirectory: value.dataStatus === "ready" ? "VERIFIED" : "AVAILABLE", admissionHistory: sourceStatus(district, "admission_history"), schedule: sourceStatus(district, "schedule"), map: sourceStatus(district, "school_coordinates"), planner: sourceStatus(district, "recommendation_inputs") === "UNAVAILABLE" ? "AVAILABLE" : sourceStatus(district, "recommendation_inputs"), sourceYear: sources.map((source) => source.schoolYear).filter(Boolean).sort().at(-1) || "", lastVerifiedAt: sources.map((source) => source.verifiedAt || source.lastCheckedAt).filter(Boolean).sort().at(-1) || "" }; }
export const capabilityRows: readonly CapabilityRow[] = Object.entries(districtMetadata.districts).map(([district, value]) => { const capability = deriveDistrictCapability(district); return { district, label: value.label, ...capability, reasons: { admissionRules: "115 官方簡章已校核；116 正式資料待公告。", schoolDirectory: "依現有學校目錄資料狀態。", admissionHistory: capability.admissionHistory === "PARTIAL" ? "僅有社群參考資料，未取得官方歷史錄取資料。" : "尚未取得可驗證的歷史錄取資料。", schedule: "目前為 115 來源年度參考；116 正式日期待公告。", map: "座標與路線依 OpenStreetMap／外部服務，仍需核對。", planner: "可建立與保存志願；不含錄取預測模型。" } }; });
export const dataChangeLog = [{ date: "2026-08-31", version: "feature-depth-batch1", dataset: "admission_history, recommendation_inputs, official_links, trust_registry", districts: "全國（歷史資料目前僅中投社群參考）", change: "建立可稽核歷史資料契約、停用落點預測、將官方入口與公告紀錄分開。", reason: "Feature Depth Remediation Batch 1", source: "FEATURE_REMEDIATION_BATCH1.md" }, { date: "2026-08-31", version: "feature-depth-batch3", dataset: "source_registry, official_information, admission_history, vocational_groups", districts: "全國", change: "建立來源快照、資料匯入驗證與年度狀態契約；保留社群資料與官方資料的邊界。", reason: "Official Data Foundation Batch 3", source: "FEATURE_REMEDIATION_BATCH3.md" }] as const;
