import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {parseCsv,validateData,normalizeSchool} from '../lib/school-data/pipeline.mjs';
import {schoolCsvSourceDir} from './school-csv-source.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const source=schoolCsvSourceDir;
const runtimeSource=path.join(root,'content/schools');
const output=path.join(root,'content/schools/generated');
const masterText=fs.readFileSync(path.join(source,'schools_master.csv'),'utf8');
const recordsText=fs.readFileSync(path.join(source,'school_admission_records.csv'),'utf8');
const master=parseCsv(masterText), records=parseCsv(recordsText);
const audit=validateData(master,records);
const schools=master.rows.map(r=>normalizeSchool(r,records.rows.filter(a=>a['學校代碼']===r['學校代碼'])));
const count=values=>Object.fromEntries([...new Set(values)].sort().map(v=>[v,values.filter(x=>x===v).length]));
const districts=count(schools.flatMap(s=>s.admissionDistricts)), sourceDistricts=count(records.rows.map(r=>r['資料來源區'])), cities=count(schools.map(s=>s.city));
const metadata={academicYear:'115',sourceUpdatedAt:'2026-09-01',schoolCount:schools.length,admissionRecordCount:records.rows.length,districtCount:Object.keys(sourceDistricts).length,admissionDistrictFilterCount:Object.keys(districts).length,cityCount:Object.keys(cities).length,schoolTypes:count(schools.map(s=>s.schoolType)),genders:count(schools.map(s=>s.gender)),ownership:count(schools.map(s=>s.ownership)),lodgingStatuses:count(schools.map(s=>s.lodgingStatus)),transportStatuses:count(schools.map(s=>s.transportStatus)),sourceDirectory:'JSHS_CSV_各區資料_2026-09-01',sourceFiles:['schools_master.csv','school_admission_records.csv'],sourceHashes:{master:crypto.createHash('sha256').update(masterText).digest('hex'),admissions:crypto.createHash('sha256').update(recordsText).digest('hex')},validation:{errors:audit.errors.length,warnings:audit.warnings.length,departmentWarnings:audit.warnings.filter(w=>w.includes('department parsing')).length}};
const mismatches=schools.flatMap(s=>s.admissionRecords.filter(r=>r.admissionOfferingType!==s.schoolType).map(r=>({schoolCode:s.code,schoolName:s.name,masterType:s.schoolType,admissionType:r.admissionOfferingType,admissionArea:r.admissionDistrict,departmentRaw:r.departmentRaw,sourceCsv:'content/schools/school_admission_records.csv',resolution:'B',resolutionNote:'共同／跨區招生關聯保留招生提供學制；學校實體學制以 schools_master.csv 為準。',unresolved:false})));
const normalizeAddress=value=>String(value||'').normalize('NFKC').replace(/^\[?\d{3,6}\]?\s*/,'').replace(/\s+/g,'').replaceAll('台','臺').replaceAll('恒','恆').replace(/[一壹]段/g,'1段').replace(/[二貳]段/g,'2段').replace(/[三參]段/g,'3段').replace(/[四肆]段/g,'4段').replace(/[五伍]段/g,'5段').replace(/[六陸]段/g,'6段').replace(/[七柒]段/g,'7段').replace(/[八捌]段/g,'8段').replace(/[九玖]段/g,'9段').replace(/[十拾]段/g,'10段').replace(/(\d+)之(\d+)/g,'$1-$2').replace(/(\d+)號之(\d+)/g,'$1-$2號').replace(/(\d+)樓/g,'$1F').replace(/\d+鄰/g,'').replace(/[号]/g,'號');
const geocodeCache=JSON.parse(fs.readFileSync(path.join(runtimeSource,'school-geocode-cache.json'),'utf8'));
const verifiedGeocodes=schools.filter(s=>{const r=geocodeCache[s.code];return r&&r.schoolCode===s.code&&r.verificationStatus==='verified'&&normalizeAddress(r.normalizedAddress)===normalizeAddress(s.address)&&Number.isFinite(r.latitude)&&Number.isFinite(r.longitude)&&(r.provider||r.sourceType)&&r.source&&r.verifiedAt;});
const geocodeQueue=JSON.parse(fs.readFileSync(path.join(runtimeSource,'geocode-review-queue.json'),'utf8'));
const geocodeRetry=fs.existsSync(path.join(runtimeSource,'geocode-retry-queue.json'))?JSON.parse(fs.readFileSync(path.join(runtimeSource,'geocode-retry-queue.json'),'utf8')):[];
const geocodeAudit={schoolCount:schools.length,verifiedCount:verifiedGeocodes.length,reviewRequiredCount:geocodeQueue.length,retryCount:geocodeRetry.length,failedCount:0,coverage:verifiedGeocodes.length/schools.length};
fs.mkdirSync(output,{recursive:true});
const write=(name,value)=>fs.writeFileSync(path.join(output,name+'.json'),JSON.stringify(value,null,2)+'\n');
const summaries=schools.map(({raw,admissionRecords,sources,address,website,phone,brochureQuota,scoreNote,transport,commute,lodging,mapUrl,academicYear,admissionDistrict,...summary})=>summary);
write('metadata',metadata);write('validation',audit);write('school-summaries',summaries);
fs.copyFileSync(path.join(source,'schools_master.csv'),path.join(output,'schools_master.csv'));
fs.copyFileSync(path.join(source,'school_admission_records.csv'),path.join(output,'school_admission_records.csv'));
fs.writeFileSync(path.join(root,'SCHOOL_TYPE_MISMATCH_AUDIT.md'),`# School Type Mismatch Audit\n\n共 ${mismatches.length} 筆招生關聯的招生提供學制與學校實體學制不同；均已明確標記為共同／跨區招生提供學制（resolution B），未將招生關聯覆寫回學校實體。未解決：${mismatches.filter(m=>m.unresolved).length}。\n\n| 學校代碼 | 學校 | 實體學制 | 招生提供學制 | 招生區 | 科系與名額 | resolution | unresolved |\n|---|---|---|---|---|---|---|---|\n${mismatches.map(m=>`| ${m.schoolCode} | ${m.schoolName} | ${m.masterType} | ${m.admissionType} | ${m.admissionArea} | ${m.departmentRaw.replaceAll('|','\\|')} | ${m.resolution} | ${m.unresolved} |`).join('\n')}\n\n來源：schools_master.csv（實體）與 school_admission_records.csv（招生關聯）。`+'\n');
write('geocode-metadata',geocodeAudit);fs.writeFileSync(path.join(source,'geocode-review-queue.json'),JSON.stringify(geocodeQueue,null,2)+'\n');
const table=obj=>Object.entries(obj).map(([k,v])=>`| ${k} | ${v} |`).join('\n');
const section=(name,obj)=>`## ${name}\n\n| 項目 | 數量 |\n|---|---:|\n${table(obj)}\n`;
fs.writeFileSync(path.join(root,'SCHOOL_DATA_AUDIT.md'),`# School Data Audit\n\n資料年度：115；來源更新日：2026-09-01。\n\n學校實體 ${schools.length}；招生關聯 ${records.rows.length}。唯一實體來源 schools_master.csv，招生區與名額關聯來源 school_admission_records.csv。學校代碼保持字串；各區名額不加總。原始欄位完整保留。\n\n${section('各就學區涵蓋學校（共同就學區可重複）',districts)}\n${section('各縣市',cities)}\n${section('學制',metadata.schoolTypes)}\n${section('公私立',metadata.ownership)}\n${section('男女校',metadata.genders)}\n${section('住宿資訊狀態',metadata.lodgingStatuses)}\n${section('交通資訊狀態',metadata.transportStatuses)}\n## 驗證\n\nSchema 與必要欄位、enum、代碼唯一性、孤立關聯：${audit.errors.length} 錯誤。\n科別解析警告：${metadata.validation.departmentWarnings}。所有未解析字串保留於 raw；不阻斷 build。\nURL 僅檢查語法，未逐一執行網站連線健康檢查。\n\n## 錯誤\n\n${audit.errors.length?audit.errors.map(x=>'- '+x).join('\n'):'無'}\n\n## 缺來源、解析與可疑資料\n\n${audit.warnings.length?audit.warnings.map(x=>'- '+x).join('\n'):'無'}\n`);
if(audit.errors.length){console.error(audit.errors.join('\n'));process.exitCode=1;}else if(!process.argv.includes('--validate')){fs.mkdirSync(path.join(root,'public/data'),{recursive:true});fs.writeFileSync(path.join(root,'public/data/schools.json'),JSON.stringify({schools:summaries})+'\n');write('schools',schools);write('schools-by-code',Object.fromEntries(schools.map(s=>[s.code,s])));write('districts',districts);write('cities',cities);write('departments',[...new Set(schools.flatMap(s=>s.departments.map(d=>d.name)))].sort());}
console.log(JSON.stringify(metadata,null,2));
