import { listDeploymentEvents, listDeploymentFiles } from "../../../db/admin-store";
import { requireAdmin } from "../auth";

export const dynamic = "force-dynamic";

export default async function DeploymentsPage() {
  await requireAdmin();
  const [files, events] = await Promise.all([listDeploymentFiles(), listDeploymentEvents()]);
  return <><section className="admin-page-heading"><div><p className="admin-eyebrow">Platform / Deployments</p><h1>網站與部署</h1><p className="admin-muted">高風險程式變更先進入待部署，再由 GitHub Actions 驗證與發布。</p></div></section><section className="admin-dashboard-grid"><Status title="Production version" value="由 GitHub Actions 管理" /><Status title="最新部署" value={events[0] ? actionLabel(events[0].action) : "尚無紀錄"} /><Status title="部署流程" value="Upload → Validate → Test → Deploy" /></section><section className="admin-panel admin-module-form"><h2>上傳程式包</h2><p className="admin-muted">上傳後只會建立待部署檔案，不會直接覆蓋 production。</p><form action="/api/admin/code-upload" method="post" encType="multipart/form-data"><label>程式包<FileInput name="program" /></label><label>修改說明<textarea name="run_note" rows={3} maxLength={700} /></label><button className="admin-button" type="submit">建立待部署項目</button></form></section><section className="admin-panel"><div className="admin-section-head"><h2>待部署項目</h2><span className="admin-badge warn">{files.length} 筆</span></div><div className="admin-deployment-list">{files.map((file) => <article key={file.id} className="admin-deployment-item"><div><strong>{file.file_name}</strong><p>{file.description || "尚未填寫修改說明"}</p><small>{file.uploaded_by} · {formatDate(file.created_at)}</small></div><div className="admin-actions"><form action="/api/admin/deployments" method="post"><input type="hidden" name="file_id" value={file.id} /><input type="hidden" name="action" value="validate" /><button className="admin-button admin-button-secondary" type="submit">驗證</button></form><form action="/api/admin/deployments" method="post"><input type="hidden" name="file_id" value={file.id} /><input type="hidden" name="action" value="test" /><button className="admin-button admin-button-secondary" type="submit">測試</button></form><form action="/api/admin/deployments" method="post"><input type="hidden" name="file_id" value={file.id} /><input type="hidden" name="action" value="deploy" /><button className="admin-button admin-button-danger" type="submit">正式部署</button></form><form action="/api/admin/deployments" method="post"><input type="hidden" name="file_id" value={file.id} /><input type="hidden" name="action" value="rollback" /><button className="admin-button admin-button-danger" type="submit">Rollback</button></form></div></article>)}{!files.length ? <p className="admin-muted">目前沒有待部署程式包。</p> : null}</div></section><section className="admin-panel"><div className="admin-section-head"><h2>部署紀錄</h2><span className="admin-badge ok">可追蹤</span></div><div className="admin-deployment-list">{events.map((event) => <div key={event.id} className="admin-deployment-item"><span><strong>{actionLabel(event.action)}</strong><small>{event.note}</small></span><span className={`admin-badge ${event.status === "failed" ? "warn" : "ok"}`}>{event.status}</span></div>)}{!events.length ? <p className="admin-muted">尚無部署事件。</p> : null}</div></section></>;
}
function Status({ title, value }: { title: string; value: string }) { return <div className="admin-dashboard-card info"><span>{title}</span><strong>{value}</strong><small>由後台部署事件追蹤</small></div>; }
function FileInput({ name }: { name: string }) { return <input name={name} type="file" required />; }
function actionLabel(action: string) { return ({ validate: "驗證", test: "測試", deploy: "正式部署", rollback: "Rollback" } as Record<string, string>)[action] || action; }
function formatDate(value: string) { return new Intl.DateTimeFormat("zh-TW", { dateStyle: "medium", timeZone: "Asia/Taipei" }).format(new Date(value)); }
