import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import districtMetadata from "../../public/it_hs/district-metadata.json";

export const metadata: Metadata = { title: "信任與支援中心", description: "了解升學資料來源、更新方式、落點限制、隱私與支援服務。", alternates: { canonical: "/trust" } };

const sections = [
  ["sources", "資料來源與更新紀錄", "知道每一筆資料從哪裡來、適用哪個學年度，以及最近一次整理時間。"],
  ["placement", "如何閱讀落點與風險", "把參考區間、推估與正式規則分開，不把不確定性包裝成保證。"],
  ["report", "資料錯誤回報", "發現學校、科別、名額或來源有誤時，提供可核對的回報方式。"],
  ["privacy", "隱私權", "說明瀏覽器暫存、規劃資料、只讀分享與搜尋引擎的處理方式。"],
  ["terms", "服務條款", "說明資料使用範圍、官方資訊優先原則與使用者責任。"],
  ["support", "支持／合作與售後", "小額支持、教育合作、服務問題、退款與聯絡入口。"],
] as const;

export default function TrustPage() {
  return <main className="min-h-screen jshs-page-shell"><SiteHeader activeHref="/trust" /><section className="jshs-hero-section"><div className="mx-auto w-[min(1120px,calc(100%-32px))] py-10 md:py-14"><p className="jshs-eyebrow">信任與支援中心</p><h1 className="mt-3 max-w-4xl">資料越多，越需要知道它的邊界。</h1><p className="mt-4 max-w-3xl text-base leading-7 jshs-muted-copy">這些頁面不是網站的附錄，而是升學決策的安全欄杆：告訴你資料如何整理、何時更新、可以怎麼使用，以及什麼情況仍要回到官方核對。</p></div></section><section className="mx-auto w-[min(1120px,calc(100%-32px))] py-10"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sections.map(([id, title, body]) => <a key={id} href={`#${id}`} className="p-5 jshs-surface-card"><span className="jshs-chip">信任說明</span><h2 className="mt-3 text-lg">{title}</h2><p className="mt-2 text-sm leading-6 jshs-muted-copy">{body}</p><span className="mt-4 block text-sm text-[var(--jshs-primary)]">查看 →</span></a>)}</div><div className="mt-8 grid gap-5"><SourceSection /><PlacementSection /><ReportSection /><PolicySection id="privacy" title="隱私權"><p>未登入時，首頁進度與部分偏好會保存在使用者的瀏覽器；我的規劃使用網站提供的識別方式保存，並設為不可被搜尋引擎索引。只讀分享使用網址片段傳遞快照，不把個人規劃放進公開搜尋頁。</p><p className="mt-3">請不要在備註中填寫身分證字號、完整地址、電話或其他不必要的敏感個資。</p></PolicySection><PolicySection id="terms" title="服務條款"><p>本站提供資料整理、試算與規劃輔助。招生資格、正式名額、報名截止時間與錄取結果，以當年度招生委員會、政府與學校公告為準。</p><p className="mt-3">使用者應自行核對適用就學區與資料年度；本站不以試算結果承諾錄取，也不取代學校或官方承辦人的資格判定。</p></PolicySection><PolicySection id="support" title="支持／合作與售後"><p>若你是學生、家長、學校、導師或教育團隊，歡迎提供資料校核、課程內容、通勤資訊與教育合作建議。</p><div className="mt-5 flex flex-wrap gap-3"><a className="px-4 py-3 text-sm jshs-button-primary" href="mailto:hello@jshs.cc">聯絡合作／回報</a><Link className="px-4 py-3 text-sm jshs-button-secondary" href="/news/parents">先看家庭討論指南</Link></div><p className="mt-4 text-xs leading-6 jshs-muted-copy">小額支持、付費服務與退款規則會在正式開放前另行公告；目前不會在首頁放置付款或會員方案。</p></PolicySection></div></section><SiteFooter /></main>;
}

function SourceSection() { const districts = Object.entries(districtMetadata.districts).slice(0, 6); return <section id="sources" className="scroll-mt-24 p-6 md:p-8 jshs-surface-card"><p className="jshs-eyebrow">SOURCES & UPDATES</p><h2 className="mt-2">資料來源與更新紀錄</h2><p className="mt-3 max-w-3xl text-sm leading-7 jshs-muted-copy">學校資料來自各區公開招生資料與校方官方來源；規則與日期以招生委員會、教育部與會考官方網站為優先。每筆資料會標示年度、狀態、來源與更新日。</p><div className="mt-5 grid gap-3 md:grid-cols-3">{districts.map(([code, district]) => <div key={code} className="rounded-2xl bg-[var(--jshs-muted-surface)] p-4"><div className="flex items-center justify-between gap-2"><strong>{district.label}</strong><span className="jshs-data-tag is-reference">{district.dataStatus === "ready" ? "已校核" : "參考"}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">{district.academicYear} 學年度 · 更新 {district.updatedAt}</p><a className="mt-3 block text-sm text-[var(--jshs-primary)]" href={district.sourceUrl} target="_blank" rel="noreferrer">官方來源 ↗</a></div>)}</div><p className="mt-5 text-xs leading-6 jshs-muted-copy">全站版本：{districtMetadata.version}；資料總更新日：{districtMetadata.updatedAt}。{districtMetadata.disclaimer}</p></section>; }
function PlacementSection() { return <PolicySection id="placement" title="如何閱讀落點與風險"><p>「已校核」代表年度、來源與欄位已整理；「參考資料」可以協助比較，但不等於正式錄取門檻；「推估」是根據歷年資料的區間，不能當成保證；「待核對」要回到官方簡章確認。</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-[var(--jshs-muted-surface)] p-4"><strong>可以做</strong><p className="mt-2 text-sm leading-6 jshs-muted-copy">比較選項、找出缺資料、設計挑戰／適中／穩定結構。</p></div><div className="rounded-2xl bg-[var(--jshs-muted-surface)] p-4"><strong>不能做</strong><p className="mt-2 text-sm leading-6 jshs-muted-copy">不能取代當年度公告、序位、名額、資格審查或正式志願送出。</p></div></div></PolicySection>; }
function ReportSection() { return <PolicySection id="report" title="資料錯誤回報"><p>回報時請附上學校代碼、欄位名稱、目前顯示內容、應修正內容與可核對的官方連結。涉及個人資格或特殊身分時，請直接詢問就讀國中承辦人。</p><div className="mt-5 flex flex-wrap gap-3"><a className="px-4 py-3 text-sm jshs-button-primary" href="mailto:hello@jshs.cc?subject=找校科資料錯誤回報">寄送錯誤回報</a><Link className="px-4 py-3 text-sm jshs-button-secondary" href="/schools">回到找校科</Link></div></PolicySection>; }
function PolicySection({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-24 p-6 md:p-8 jshs-surface-card"><p className="jshs-eyebrow">TRUST & SUPPORT</p><h2 className="mt-2">{title}</h2><div className="mt-4 max-w-3xl text-sm leading-7 text-slate-600">{children}</div></section>; }
