import { getMemberSession } from "../../../lib/member-auth";
import { deleteMockExam, listMockExams, saveMockExam } from "../../../db/mock-exam-store";

export const dynamic = "force-dynamic";

export async function GET() { const member = await getMemberSession(); if (!member) return Response.json({ ok: false, error: "member_required" }, { status: 401 }); const rows = await listMockExams(member.lineUserId); return Response.json({ ok: true, records: rows.map(toPublic) }, { headers: { "cache-control": "no-store" } }); }
export async function POST(request: Request) { const member = await getMemberSession(); if (!member) return Response.json({ ok: false, error: "member_required" }, { status: 401 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body || typeof body.id !== "string" || typeof body.name !== "string" || typeof body.date !== "string" || typeof body.subjects !== "object") return Response.json({ ok: false, error: "invalid_record" }, { status: 400 }); const now = new Date().toISOString(); await saveMockExam({ id: body.id.slice(0, 80), line_user_id: member.lineUserId, name: body.name.trim().slice(0, 120), exam_date: body.date.slice(0, 10), subjects_json: JSON.stringify(body.subjects), essay: typeof body.essay === "string" ? body.essay.slice(0, 40) : "", created_at: typeof body.createdAt === "string" ? body.createdAt : now, updated_at: now }); return Response.json({ ok: true }); }
export async function DELETE(request: Request) { const member = await getMemberSession(); if (!member) return Response.json({ ok: false, error: "member_required" }, { status: 401 }); const body = await request.json().catch(() => null) as { id?: unknown } | null; if (typeof body?.id !== "string") return Response.json({ ok: false, error: "id_required" }, { status: 400 }); await deleteMockExam(member.lineUserId, body.id); return Response.json({ ok: true }); }
function toPublic(row: { id: string; name: string; exam_date: string; subjects_json: string; essay: string; created_at: string }) { let subjects: Record<string, number | null> = {}; try { subjects = JSON.parse(row.subjects_json) as Record<string, number | null>; } catch { /* preserve an honest empty record */ } return { id: row.id, name: row.name, date: row.exam_date, subjects, essay: row.essay, createdAt: row.created_at }; }
