import { getMemberSession } from "../../../lib/member-auth";
import { deleteMockExam, listMockExams, saveMockExam } from "../../../db/mock-exam-store";

export const dynamic = "force-dynamic";

export async function GET() { const member = await getMemberSession(); if (!member) return Response.json({ ok: false, error: "member_required" }, { status: 401 }); const rows = await listMockExams(member.lineUserId); return Response.json({ ok: true, records: rows.map(toPublic) }, { headers: { "cache-control": "no-store" } }); }
export async function POST(request: Request) { const member = await getMemberSession(); if (!member) return Response.json({ ok: false, error: "member_required" }, { status: 401 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; const validation = validateRecord(body); if (!validation.ok) return Response.json({ ok: false, error: validation.error }, { status: 400 }); const now = new Date().toISOString(); await saveMockExam({ id: validation.record.id, line_user_id: member.lineUserId, name: validation.record.name, exam_date: validation.record.date, subjects_json: JSON.stringify(validation.record.subjects), essay: validation.record.essay, created_at: typeof body?.createdAt === "string" && !Number.isNaN(Date.parse(body.createdAt)) ? body.createdAt : now, updated_at: now }); return Response.json({ ok: true }); }
export async function DELETE(request: Request) { const member = await getMemberSession(); if (!member) return Response.json({ ok: false, error: "member_required" }, { status: 401 }); const body = await request.json().catch(() => null) as { id?: unknown; all?: unknown } | null; if (body?.all === true) { const records = await listMockExams(member.lineUserId); await Promise.all(records.map((record) => deleteMockExam(member.lineUserId, record.id))); return Response.json({ ok: true }); } if (typeof body?.id !== "string" || !body.id.trim()) return Response.json({ ok: false, error: "id_required" }, { status: 400 }); await deleteMockExam(member.lineUserId, body.id.slice(0, 80)); return Response.json({ ok: true }); }
function validateRecord(body: Record<string, unknown> | null) { if (!body || typeof body.id !== "string" || typeof body.name !== "string" || typeof body.date !== "string" || !body.subjects || typeof body.subjects !== "object" || Array.isArray(body.subjects)) return { ok: false as const, error: "invalid_record" }; const date = body.date; const parsedDate = new Date(`${date}T00:00:00Z`); if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || Number.isNaN(parsedDate.getTime()) || parsedDate.toISOString().slice(0, 10) !== date) return { ok: false as const, error: "invalid_date" }; const source = body.subjects as Record<string, unknown>; const allowed = ["國文", "數學", "英文", "社會", "自然"]; const subjects: Record<string, number | null> = {}; for (const key of allowed) { const value = source[key]; if (value === "" || value === null || value === undefined) subjects[key] = null; else if (typeof value !== "number" || !Number.isInteger(value) || value < 0 || value > 100) return { ok: false as const, error: "invalid_subject_score" }; else subjects[key] = value; } const name = body.name.trim().slice(0, 120); if (!name) return { ok: false as const, error: "invalid_name" }; return { ok: true as const, record: { id: body.id.slice(0, 80), name, date, subjects, essay: typeof body.essay === "string" ? body.essay.trim().slice(0, 40) : "" } }; }
function toPublic(row: { id: string; name: string; exam_date: string; subjects_json: string; essay: string; created_at: string; updated_at: string }) { let subjects: Record<string, number | null> = {}; try { subjects = JSON.parse(row.subjects_json) as Record<string, number | null>; } catch { /* preserve an honest empty record */ } return { id: row.id, name: row.name, date: row.exam_date, subjects, essay: row.essay, createdAt: row.created_at, updatedAt: row.updated_at }; }
